spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardPrj
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update